---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: kitchen

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-7.2
    driver:
      box: packer_centos7_virtualbox
      box_url: ~/packer_vbox_builds/packer_centos7_virtualbox.box

suites:
  - name: primary
    run_list:
      - recipe[custom_mysql::default]
      - role[mysql-primary]
    attributes:
      mysql-multi:
        slaves: ['33.33.33.72']
    driver_config:
      network:
        - ['private_network', {ip: '33.33.33.71'}]
  - name: backup
    run_list:
      - recipe[custom_mysql::default]
      - role[mysql-backup]
    attributes:
      mysql-multi:
        master: '33.33.33.71'
    driver_config:
      network:
        - ['private_network', {ip: '33.33.33.72'}]
