name 'custom_mysql'
maintainer 'The Authors'
maintainer_email 'roy.crombleholme@pam-it.com'
license 'all_rights'
description 'Installs/Configures custom_mysql'
long_description 'Installs/Configures custom_mysql'
version '0.1.0'

depends 'firewalld', '~> 1.1.1'
depends 'mysql-multi', '~> 1.4.3'
